### ISSUE TITLE
Ramtop

### ISSUE THREAD

**Issue by Jobd0ne** [SimonGreenaway/sQLux-menu#11]
Ramtop accepts any number including negative ones.

**Comment by SimonGreenaway** [comment]
CPU_HOG option doesn't seem to make any difference - sqlUX still runs 100% on one core whether it's set to 1 or 0. Therefore not sure what the default option should be! (I won't write to ini for the default).

**Comment by SimonGreenaway** [comment]
Changed to always write CPU_HOG to ini at the moment.

**Comment by SimonGreenaway** [comment]
Added error checking, now sets to 256k if negative or not a number.
