### ISSUE TITLE
Resolution issue

### ISSUE THREAD

**Issue by Jobd0ne** [SimonGreenaway/sQLux-menu#2]
When entering a resolution in the GUI, then clicking save, the GUI throws an error and creates an ini of rubbish. see attachment
[new.ini.txt](https://github.com/user-attachments/files/17168817/new.ini.txt)
![Screenshot from 2024-09-27 20-32-02](https://github.com/user-attachments/assets/e3219b85-2efc-4a82-9223-deb87a5d8fe1)

**Comment by SimonGreenaway** [comment]
Fixed with  v0.2
