### ISSUE TITLE
Verbosity

### ISSUE THREAD

**Issue by Jobd0ne** [SimonGreenaway/sQLux-menu#21]
VERBOSITY 3 in the ini does not do what -v 3 does in the cli. Manually editing VERBOSITY = 3 to V=3 in the ini works. I looked this up , the correct syntax is not VERBOSITY, but 'VERBOSE = 3'

**Comment by SimonGreenaway** [comment]
I wondered why I didn't change

**Comment by SimonGreenaway** [comment]
Fixed, new version uploaded as v0.9
