### ISSUE TITLE
No option to select Spanish keyboard

### ISSUE THREAD

**Issue by ikjordan** [SimonGreenaway/sQLux-menu#27]
The "comfy chair" sQLux release (v1.0.7b) added support for a Spanish keyboard.

It is selected with the line

`KBD = ES `

But `ES` is not an option in the GUI - so `US` is displayed instead and `US` is written back when the `.ini` file is saved.

**Comment by SimonGreenaway** [comment]
Fixed in next release. (Thanks for the reports, will work through them!)
