### ISSUE TITLE
Full path to executable not read in Windows

### ISSUE THREAD

**Issue by ikjordan** [SimonGreenaway/sQLux-menu#29]
In Windows an `sqlux.ini` containing a full valid path to the` sqlux.exe` file was created. However, when the Run! option is selected the error "Cannot find sQLux binary here:" is displayed. 

The valid full path was: `D:\Development\QL\sQLux\sqlux.exe`

but the error message gave ` D:\Development\QL\sQLux\sqlux` i.e. the `.exe` extension was stripped.

The executable was found if passed on the command line i.e: `java -jar SqluxMenu.jar -s d:/Development/Ql/sQLux/sQLux.exe`

**Comment by SimonGreenaway** [comment]
That feature was decorative, but didn't do anything. Now  fixed on next version.
