### ISSUE TITLE
ini file specified on command line not opened in Windows

### ISSUE THREAD

**Issue by ikjordan** [SimonGreenaway/sQLux-menu#30]
Launched sQLux-menu with the following: `java -jar SqluxMenu.jar -i d:/Development/Ql/sQLux/sQLux.ini` 
where `d:/Development/Ql/sQLux/sQLux.ini` was the path to a valid `.ini` file. 

However, sQLux-menu started with empty data, i.e. the `.ini` file was not read

The file is parsed correctly if it is loaded via the `File Open ini...` menu option.

**Comment by SimonGreenaway** [comment]
You could only load an ini from -i that was in the ini directory. Corrected for next version.
